apiVersion: constraints.gatekeeper.sh/v1beta1
kind: K8sDenyImageTags
metadata:
  name: denyimagetags
spec:
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
    parameters:
      tags:
        - "latest"